/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />
/// <reference types="@sveltejs/kit" />

import { build, files, prerendered, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

// Cache name with deployment version for automatic invalidation
const CACHE_NAME = `przystaneczki-cache-v${version}`;

// App assets generated by Vite and static files
const ASSETS = [...build, ...files, ...prerendered];

sw.addEventListener('install', (event) => {
	// Precaches all build and static assets
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => sw.skipWaiting())
	);
});

sw.addEventListener('activate', (event) => {
	// Delete any old caches that don't match the current version
	event.waitUntil(
		caches
			.keys()
			.then(async (keys) => {
				for (const key of keys) {
					if (key !== CACHE_NAME) {
						await caches.delete(key);
					}
				}
				await sw.clients.claim();
			})
	);
});

sw.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		sw.skipWaiting();
	}
});

sw.addEventListener('fetch', (event) => {
	// Only handle GET requests
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Only handle http/https schemes (ignore chrome-extension, etc.)
	if (!url.protocol.startsWith('http')) return;

	// CRITICAL FOR AZURE KEEP-ALIVE & LIVE TRANSIT DATA:
	// Do NOT cache API endpoints or version checks!
	// These requests MUST reach Azure Node.js server directly to keep the free-tier container alive
	// and ensure departures are real-time.
	if (url.pathname.startsWith('/api/') || url.pathname.includes('/version.json')) {
		return;
	}

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// 1. Static built assets and public files (Cache First)
			if (ASSETS.includes(url.pathname)) {
				const cachedResponse = await cache.match(url.pathname);
				if (cachedResponse) {
					return cachedResponse;
				}
			}

			// 2. Navigation requests (Network First, fallback to cached page or /)
			if (event.request.mode === 'navigate') {
				try {
					const networkResponse = await fetch(event.request);
					if (networkResponse.status === 200) {
						cache.put(event.request, networkResponse.clone());
					}
					return networkResponse;
				} catch {
					const cachedResponse = await cache.match(event.request);
					if (cachedResponse) {
						return cachedResponse;
					}
					const fallback = await cache.match('/');
					if (fallback) {
						return fallback;
					}
				}
			}

			// 3. For any other GET request (Network First, Cache Fallback)
			try {
				const response = await fetch(event.request);
				if (response.status === 200 && !response.headers.get('cache-control')?.includes('no-store')) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch (err) {
				const cachedResponse = await cache.match(event.request);
				if (cachedResponse) {
					return cachedResponse;
				}
				throw err;
			}
		})()
	);
});
